SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS UADMP;
DROP TABLE IF EXISTS ADDMT;
DROP TABLE IF EXISTS AURMP;
DROP TABLE IF EXISTS AUTMT;
DROP TABLE IF EXISTS CTYMT;
DROP TABLE IF EXISTS STEMT;
DROP TABLE IF EXISTS CNTMT;
DROP TABLE IF EXISTS ITMT;
DROP TABLE IF EXISTS UTRMP;
DROP TABLE IF EXISTS ROLMT;
DROP TABLE IF EXISTS UTAMP;
DROP TABLE IF EXISTS UACMT;
DROP TABLE IF EXISTS USRMT;
DROP TABLE IF EXISTS UTYMT;




/* Create Tables */

-- Address Master
CREATE TABLE ADDMT
(
	-- Address ID
	ADID  NOT NULL COMMENT 'Address ID',
	-- Landmark
	LDMK  COMMENT 'Landmark',
	-- Locality
	LCLT  COMMENT 'Locality',
	-- City ID
	CTID  NOT NULL COMMENT 'City ID',
	-- Pincode
	PIN  COMMENT 'Pincode',
	PRIMARY KEY (ADID)
) COMMENT = 'Address Master';


CREATE TABLE AURMP
(
	-- Mapping ID
	MPID  NOT NULL COMMENT 'Mapping ID',
	-- Role ID
	RLID  NOT NULL COMMENT 'Role ID',
	-- Auth ID
	AUID  NOT NULL COMMENT 'Auth ID',
	PRIMARY KEY (MPID)
);


-- Auth Master
CREATE TABLE AUTMT
(
	-- Auth ID
	AUID  NOT NULL COMMENT 'Auth ID',
	PRIMARY KEY (AUID)
) COMMENT = 'Auth Master';


CREATE TABLE CNTMT
(
	-- Country ID
	CRID  NOT NULL COMMENT 'Country ID',
	-- Country
	CTRY  COMMENT 'Country',
	PRIMARY KEY (CRID)
);


-- City Master
CREATE TABLE CTYMT
(
	-- City ID
	CTID  NOT NULL COMMENT 'City ID',
	-- City Name
	CITY  COMMENT 'City Name',
	-- State ID
	STID  NOT NULL COMMENT 'State ID',
	PRIMARY KEY (CTID)
) COMMENT = 'City Master';


-- Intent Type Master Table
CREATE TABLE ITMT
(
	ITID  NOT NULL,
	-- Description
	DESC  COMMENT 'Description',
	PRIMARY KEY (ITID)
) COMMENT = 'Intent Type Master Table';


-- Role Master
CREATE TABLE ROLMT
(
	-- Role ID
	RLID  NOT NULL COMMENT 'Role ID',
	-- Description
	DESC  COMMENT 'Description',
	PRIMARY KEY (RLID)
) COMMENT = 'Role Master';


-- State Master
CREATE TABLE STEMT
(
	-- State ID
	STID  NOT NULL COMMENT 'State ID',
	STAT ,
	-- Country ID
	CRID  NOT NULL COMMENT 'Country ID',
	PRIMARY KEY (STID)
) COMMENT = 'State Master';


CREATE TABLE UACMT
(
	-- Account ID
	ACID  NOT NULL COMMENT 'Account ID',
	-- User Name
	UNAM  COMMENT 'User Name',
	-- Password
	UPWD  COMMENT 'Password',
	-- User ID
	USID  COMMENT 'User ID',
	PRIMARY KEY (ACID)
);


-- User Master - Address Master Mapping
CREATE TABLE UADMP
(
	-- Mapping ID
	MPID  NOT NULL COMMENT 'Mapping ID',
	USID  NOT NULL,
	-- Address ID
	ADID  NOT NULL COMMENT 'Address ID',
	PRIMARY KEY (MPID),
	UNIQUE (MPID, USID, ADID)
) COMMENT = 'User Master - Address Master Mapping';


-- User Master Table
CREATE TABLE USRMT
(
	USID  NOT NULL,
	PRIMARY KEY (USID)
) COMMENT = 'User Master Table';


-- User Type - Account Mapping
CREATE TABLE UTAMP
(
	-- Mapping ID
	MPID  NOT NULL COMMENT 'Mapping ID',
	-- User Type ID
	UTID  NOT NULL COMMENT 'User Type ID',
	-- Account ID
	ACID  NOT NULL COMMENT 'Account ID',
	PRIMARY KEY (MPID)
) COMMENT = 'User Type - Account Mapping';


-- User Type Role Mapping
CREATE TABLE UTRMP
(
	-- Mapping ID
	MPID  NOT NULL COMMENT 'Mapping ID',
	-- User Type ID
	UTID  NOT NULL COMMENT 'User Type ID',
	-- Role ID
	RLID  NOT NULL COMMENT 'Role ID',
	PRIMARY KEY (MPID)
) COMMENT = 'User Type Role Mapping';


-- User Type Master
CREATE TABLE UTYMT
(
	-- User Type ID
	UTID  NOT NULL COMMENT 'User Type ID',
	-- Description
	DESC  COMMENT 'Description',
	PRIMARY KEY (UTID)
) COMMENT = 'User Type Master';



/* Create Foreign Keys */

ALTER TABLE UADMP
	ADD FOREIGN KEY (ADID)
	REFERENCES ADDMT (ADID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AURMP
	ADD FOREIGN KEY (AUID)
	REFERENCES AUTMT (AUID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE STEMT
	ADD FOREIGN KEY (CRID)
	REFERENCES CNTMT (CRID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ADDMT
	ADD FOREIGN KEY (CTID)
	REFERENCES CTYMT (CTID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE AURMP
	ADD FOREIGN KEY (RLID)
	REFERENCES ROLMT (RLID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE UTRMP
	ADD FOREIGN KEY (RLID)
	REFERENCES ROLMT (RLID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CTYMT
	ADD FOREIGN KEY (STID)
	REFERENCES STEMT (STID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE UTAMP
	ADD FOREIGN KEY (ACID)
	REFERENCES UACMT (ACID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE UACMT
	ADD FOREIGN KEY (USID)
	REFERENCES USRMT (USID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE UADMP
	ADD FOREIGN KEY (USID)
	REFERENCES USRMT (USID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE UTAMP
	ADD FOREIGN KEY (UTID)
	REFERENCES UTYMT (UTID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE UTRMP
	ADD FOREIGN KEY (UTID)
	REFERENCES UTYMT (UTID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



